scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params: # Blue 0.3 2.9 Red -2.9 -0.3
        lower_angle: 0.3
        upper_angle: 2.9

sllidar_node:
  ros__parameters:
    serial_port: /dev/ttyUSB6
    inverted: True # Blue True Red False
