scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 0.3
        upper_angle: 2.9

sllidar_node:
  ros__parameters:
    serial_port: /dev/ttyUSB5
